apps/brew/urls.py
from django.urls import re_path
from django.contrib.auth.decorators import login_required
from .views import *
from .forms import *
from .models import *

urlpatterns = [
    re_path(r'^add/$',
        RecipeCreateView.as_view(),
        name='brew_recipe_add'),

    re_path(r'^import/$',
        RecipeImportView.as_view(),
        name='brew_recipe_import'),

    re_path(r'^export/$',
        RecipeExportView.as_view(),
        name='brew_recipe_export'),

    re_path(r'^user/(?P<username>\w+)/$',
        RecipeListView.as_view(),
        name='brew_recipe_user'),

    re_path(r'^my-recipes/$',
        login_required(UserRecipeListView.as_view()),
        name='brew_recipe_owner'),

    re_path(r'^user/$',
        UserListView.as_view(),
        name='brew_recipe_users'),

    re_path(r'^by-style/$',
        StyleRecipesView.as_view(),
        name="brew_recipe_styles"),

    re_path(r'^by-style/(?P<slug>[\w-]+)-(?P<pk>\d+)/$',
        StyleRecipeView.as_view(),
        name="brew_recipe_style"),

    re_path(r'^(?P<pk>\d+)-(?P<slug>[\w-]+)/$',
        RecipeDetailView.as_view(),
        name='brew_recipe_detail'),

    re_path(r'^(?P<pk>\d+)-(?P<slug>[\w-]+)/comments/$',
        RecipeDetailView.as_view(page="comments"),
        name='brew_recipe_comments'),

    re_path(r'^(?P<pk>\d+)-(?P<slug>[\w-]+)/permissions/$',
        RecipeDetailView.as_view(page="permissions"),
        name='brew_recipe_permissions'),

    re_path(r'^(?P<recipe_id>\d+)-(?P<slug>[\w-]+)/permissions/set/$',
        set_user_perm,
        name='brew_recipe_setperms'),

    re_path(r'^(?P<pk>\d+)-(?P<slug>[\w-]+)/print/$',
        RecipeDetailView.as_view(page="print"),
        name='brew_recipe_print'),

    re_path(r'^(?P<pk>\d+)-(?P<slug>[\w-]+)/text/$',
        RecipeDetailView.as_view(page="text"),
        name='brew_recipe_text'),

    re_path(r'^(?P<recipe_id>\d+)-(?P<slug>[\w-]+)/confirm-delete/$',
        RecipeDeleteView.as_view(),
        name='brew_recipe_delete'),

    re_path(r'^(?P<recipe_id>\d+)-(?P<slug>[\w-]+)/destock/$',
        RecipeDestockView.as_view(),
        name='brew_recipe_destock'),

    re_path(r'^(?P<recipe_id>\d+)-(?P<slug>[\w-]+)/edit/$',
        RecipeUpdateView.as_view(),
        name='brew_recipe_edit'),

    re_path(r'^(?P<recipe_id>\d+)-(?P<slug>[\w-]+)/clone/$',
        RecipeCloneView.as_view(),
        name='brew_recipe_clone'),

    re_path(r'^(?P<recipe_id>\d+)-(?P<slug>[\w-]+)/calculator$',
        RecipeEfficiencyCalculatorView.as_view(),
        name='brew_recipe_efficiency_calculator'),

    re_path(r'^(?P<recipe_id>\d+)/add/(?P<ingredient>\w+)/$',
        IngredientCreateView.as_view(),
        name='brew_recipe_addingredient'),

    re_path(r'^(?P<recipe_id>\d+)/remove/(?P<ingredient>\w+)/(?P<object_id>\d+)/$',
        remove_ingredient,
        name='brew_recipe_removeingredient'),

    re_path(r'^(?P<recipe_id>\d+)/edit/(?P<ingredient>\w+)/(?P<object_id>\d+)/$',
        IngredientUpdateView.as_view(),
        name='brew_recipe_editingredient'),

    re_path(r'^(?P<recipe_id>\d+)/mash/add/$',
        MashCreateView.as_view(),
        name="brew_mash_add"),

    re_path(r'^(?P<recipe_id>\d+)/mash/(?P<object_id>\d+)/edit/$',
        MashUpdateView.as_view(),
        name="brew_mash_edit"),

    re_path(r'^(?P<recipe_id>\d+)/mash/(?P<object_id>\d+)/delete/$',
        mash_delete,
        name="brew_mash_delete"),

    re_path(r'^guide/style/$',
        StyleListView.as_view(),
        name="brew_style_list"),

    re_path(r'^guide/style/(?P<pk>\d+)/$',
        StyleDetailView.as_view(),
        name="brew_style_detail")
]

apps/units/urls.py
from django.urls import re_path
from units import views

urlpatterns = [
    re_path(r'^set/(?P<unit>\w+)/(?P<locale>\w+)/$', views.set_unit, name='unit_set'),

]

zython/urls.py
from django.conf.urls.static import static
from django.urls import re_path, include, path
from django.conf import settings
from django.contrib import admin
from django.views.generic import TemplateView
from brew.views.recipe import RecipeListView
import accounts.views
from public.views import comment_delete

admin.autodiscover()

urlpatterns = [

    re_path(r'^$',
        RecipeListView.as_view(),
        name='root_url'),

    re_path(r"^account/login/$",
        accounts.views.LoginView.as_view(),
        name="account_login"),

    re_path(r"^account/signup/$",
        accounts.views.SignupView.as_view(),
        name="account_signup"),

    re_path(r"^account/settings/$",
        accounts.views.SettingsView.as_view(),
        name="account_settings"),

    re_path(r"^account/new-social-auth-user/$",
        accounts.views.new_socialuser,
        name="account_new_socialuser"),

    re_path(r'^comment-delete/(\d+)/',
        comment_delete,
        name="comment-delete"),

    re_path(r'^how-it-works/',
        TemplateView.as_view(template_name="how.html"),
        name="how_it_works"),

    re_path(r'^authors-and-tippers/',
        TemplateView.as_view(template_name="authors-and-tippers.html"),
        name="authors_and_tippers"),

    re_path(r'login/recipe/$',
        RecipeListView.as_view(),
        name="login_recipe"),

    re_path(r'^email_test/',
        TemplateView.as_view(template_name="base_email.html"),
        name="dfgfdg"),

    re_path(r"^account/", include("account.urls")),
    re_path(r'^recipe/', include('brew.urls')),
    re_path(r'^stocks/', include('stocks.urls')),
    re_path(r'^units/', include('units.urls')),
    re_path(r'^comments/', include('django_comments.urls')),
    re_path(r'^i18n/', include('django.conf.urls.i18n')),
    path('captcha/', include('captcha.urls')),
    path('admin/', admin.site.urls),

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

apps/brew/models.py
import math
import random
from operator import itemgetter
from datetime import datetime
from django.db import models
from django.db.models import Sum
from django.utils.translation import ugettext_lazy as _
from django.contrib.auth.models import User
from django_comments.signals import comment_was_posted
from django.contrib.contenttypes.models import ContentType
from django.conf import settings
from django.core.cache import cache
from django.template.loader import render_to_string
from django.utils.text import slugify
from django.urls import reverse
from public.helpers import send_email_html
from units.conversions import kg_to_lb, ebc_to_srm, \
    srm_to_ebc, l_to_gal, g_to_oz, f_to_c, c_to_f

from .fields import BitternessField, GravityField, ColorField
from .models_base import *
from . import formulas
from .managers import RecipeManager, BeerStyleManager
from . import settings as app_settings


__all__ = (
    'RECIPE_TYPE_CHOICES', 'MISC_TIME_CHOICES',
    'MASH_TYPE_CHOICES', 'BeerStyle', 'Recipe',
    'Malt', 'Hop', 'Misc', 'Yeast',
    'RecipeMalt', 'RecipeHop', 'RecipeMisc', 'RecipeYeast',
    'MashStep'
)

RECIPE_TYPE_CHOICES = (
    ('allgrain', _("All grain")),
    ('partial', _("Partial mash")),
    ('extract', _("Extract")),
    ('adjunct', _("Adjunct")),
    ('sugar', _("Sugar"))
)

MISC_TIME_CHOICES = (
    ('min', _('Mins')),
    ('hours', _('Hours')),
    ('days', _('Days')),
    ('weeks', _('Weeks'))
)

MASH_TYPE_CHOICES = (
    ('infusion', _('Infusion')),
    ('decoction', _('Decoction')),
    ('temperature', _('Temperature'))
)


class BeerStyle(models.Model):
    name = models.CharField(max_length=200)
    category = models.CharField(max_length=200)
    guide = models.CharField(max_length=200)
    number = models.IntegerField()
    sub_number = models.CharField(max_length=1)

    # Ranges
    original_gravity_min = GravityField()
    original_gravity_max = GravityField()
    final_gravity_min = GravityField()
    final_gravity_max = GravityField()
    bitterness_min = BitternessField()
    bitterness_max = BitternessField()
    color_min = ColorField()
    color_max = ColorField()
    alcohol_min = models.DecimalField(max_digits=4, decimal_places=2)
    alcohol_max = models.DecimalField(max_digits=4, decimal_places=2)

    # Notes
    description = models.TextField(blank=True, null=True)
    profile = models.TextField(blank=True, null=True)
    ingredients = models.TextField(blank=True, null=True)
    examples = models.TextField(blank=True, null=True)

    objects = BeerStyleManager()

    def get_slug(self):
        return u"%s" % slugify(self.name)

    def get_number(self):
        return "%s.%s" % (self.number, self.sub_number)

    def __str__(self):
        return "%s - %s" % (self.get_number(), self.name)

    def is_outdated(self):
        return self.guide != settings.ACTIVE_BJCP_YEAR

    def get_dated_name(self):
        """
        Returns the name and if the style is outdated, the guide year is added at the end.
        """
        name_elmts = [self.get_number(), self.name]
        if self.is_outdated():
            name_elmts.append(self.guide)
        return " - ".join(name_elmts)

    def get_absolute_url(self):
        return reverse('brew_style_detail', args=[self.id])

    def og_range(self):
        return [self.original_gravity_min, self.original_gravity_max]

    def fg_range(self):
        return [self.final_gravity_min, self.final_gravity_max]

    def ibu_range(self):
        return [self.bitterness_min, self.bitterness_max]

    def color_range(self):
        return [self.color_min, self.color_max]

    def alcohol_range(self):
        return [self.alcohol_min, self.alcohol_max]


    class Meta:
        ordering = ('number', 'sub_number')


class Recipe(models.Model):
    """
    The main beer recipe
    """
    name = models.CharField(_('Name'), max_length=100)
    slug_url = models.SlugField(null=True, blank=True, default="zython")
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True, blank=True)
    batch_size = models.DecimalField(_('Batch size'), max_digits=8, decimal_places=1, help_text="L")
    style = models.ForeignKey('BeerStyle', verbose_name=_('Style'), blank=True, null=True, on_delete=models.SET_NULL)
    recipe_type = models.CharField(_('Type'), choices=RECIPE_TYPE_CHOICES, default="allgrain", max_length=50)
    mes_original_gravity = GravityField(null=True, blank=True)
    mes_final_gravity = GravityField(null=True, blank=True)
    mes_alcohol = models.DecimalField(max_digits=3, decimal_places=1, default="0.0")

    # - - -
    # Preferences
    private = models.BooleanField(_(u'Private recipe ?'), default=False, help_text=_(u"If checked, this recipe will not be listed to other users."))
    notes = models.TextField(_('Notes'), null=True, blank=True)
    efficiency = models.DecimalField(_('Efficiency'), max_digits=4, decimal_places=1, default="75", help_text="%")
    mash_tun_deadspace = models.DecimalField(_('Mash tun deadspace'), max_digits=7, decimal_places=1, help_text="L", default="1.5")
    boiler_tun_deadspace = models.DecimalField(_('Boiler tun deadspace'), max_digits=7, decimal_places=1, help_text="L", default="1.5")
    evaporation_rate = models.DecimalField(_('Evaporation rate'), max_digits=5, decimal_places=2, help_text="%", default="8")
    grain_temperature = models.DecimalField(_('Grain temperature'), max_digits=3, decimal_places=1, default="22")
    forked_from = models.ForeignKey('self', null=True, blank=True, on_delete=models.SET_NULL)
    last_destock_datetime = models.DateTimeField(null=True, blank=True)

    objects = RecipeManager()

    # - - -
    # Generic model class/methods

    def update_slug_url(self, force_update=True):
        """
        * force_update (bool) : if True will update self.slug_url everytime. If False, won't update if slug_url is not None
        """
        if force_update or not self.slug_url:
            self.slug_url = slugify(u"%s" % self.name)[:49]
            if not self.slug_url:
                self.slug_url = str(self.id)
            self.save()

    def can_be_viewed_by_user(self, user):
        if self.private and user != self.user and not user.has_perm('brew.view_recipe', self):
            return False
        else:
            return True

    def clone_to_user(self, user):
        this_recipe = Recipe.objects.get(pk=self.pk)
        new_recipe = self
        new_recipe.pk = None
        new_recipe.user = user
        new_recipe.forked_from = this_recipe
        new_recipe.last_destock_datetime = None
        new_recipe.save()
        reversed_relations = ("recipemalt_set", "recipehop_set", "recipeyeast_set", "mashstep_set", "recipemisc_set")
        for rel in reversed_relations:
            children = getattr(this_recipe, rel).all()
            for child in children:
                child.pk = None
                child.recipe = new_recipe
                child.save()
        return new_recipe

    def guess_style(self):
        """
        According to the OG, FG, ABV, IBU and EBC,
        will return a queryset of corresponding Style
        """
        og = self.get_original_gravity()
        fg = self.get_final_gravity()
        abv = self.get_abv()
        ibu = self.get_ibu()
        ebc = self.get_ebc()
        return BeerStyle.objects.filter(
            original_gravity_min__lte=og,
            original_gravity_max__gte=og,
            final_gravity_min__lte=fg,
            final_gravity_max__gte=fg,
            alcohol_min__lte=abv,
            alcohol_max__gte=abv,
            bitterness_min__lte=ibu,
            bitterness_max__gte=ibu,
            color_min__lte=ebc,
            color_max__gte=ebc,
        )

    def zython_advice_color(self):
        ebc = self.get_ebc()
        advices = []
        if ebc < 3:
            advices = [
                _(u"Looks so clear !!"),
                _(u"This beer makes me thirsty, almost transparent :)"),
                _(u"A brighter beer will be invisible"),
            ]
        elif ebc < 10:
            advices = [
                _(u"I love blonds !!"),
                _(u"A regular blond beer"),
                _(u"This color is fine"),
            ]
        elif ebc < 20:
            advices = [
                _(u"Looks like gold, good job !"),
                _(u"A fresh light-amber, yummy"),
                _(u"This beer looks serious, gold !"),
            ]
        elif ebc < 30:
            advices = [
                _(u"This beer has a great amber color"),
                _(u"A fresh dark-amber, sooo yummy"),
                _(u"This color is perfect for dark ambers"),
            ]
        elif ebc < 50:
            advices = [
                _(u"Yeaahh, a brown beer"),
                _(u"Nice job, this beer is not that dark, just great !"),
                _(u"Someone just made a prefect brown beer"),
            ]
        elif ebc < 100:
            advices = [
                _(u"That's pretty dark"),
                _(u"We can't anything see through this beer excepting the fact that it looks dark"),
                _(u"Black, perfectly black."),
            ]
        elif ebc >= 100:
            advices = [
                _(u"An oil well"),
                _(u"Are you sure this beer should be that dark ?"),
                _(u"Am I blind or this beer is black ?")
            ]
        if advices:
            return random.choice(advices)
        else:
            return ""

    @property
    def cache_key(self):
        # TODO:
        # I consider modifying the cache_key system to have a unique
        # key each time the object is saved.
        modified = self.modified or datetime.now()
        return "%s_%s" % (self.id, modified.strftime('%Y%m%d%H%M%S%f'))

    def __str__(self):
        return self.name

    def get_absolute_url(self):

apps/brew/views/base.py
from django import http
from django.utils.decorators import method_decorator
from django.contrib.auth.mixins import LoginRequiredMixin

from ..decorators import recipe_author
from ..models import Recipe, RecipeHop, RecipeMalt, RecipeMisc, RecipeYeast, Malt, Misc, Hop, Yeast
from ..forms import RecipeMaltForm, RecipeHopForm, RecipeMiscForm, RecipeYeastForm

SLUG_MODEL = {
    'malt': RecipeMalt,
    'misc': RecipeMisc,
    'hop': RecipeHop,
    'yeast': RecipeYeast
}

SLUG_MODELROOT = {
    'malt': Malt,
    'misc': Misc,
    'hop': Hop,
    'yeast': Yeast
}

SLUG_MODELFORM = {
    'malt': RecipeMaltForm,
    'misc': RecipeMiscForm,
    'hop': RecipeHopForm,
    'yeast': RecipeYeastForm
}


class RecipeAuthorMixin(LoginRequiredMixin):
    '''
    Mixin object to authorise recipe author
    acessing views (deletion, updates...)
    '''
    model = Recipe
    pk_url_kwarg = 'recipe_id'

    @method_decorator(recipe_author)
    def dispatch(self, request, recipe, *args, **kwargs):
        self.recipe = recipe
        return super(RecipeAuthorMixin, self).dispatch(request, *args, **kwargs)


class RecipeViewableMixin(object):
    """
    The recipe can be viewed by the current user
    """
    model = Recipe
    pk_url_kwarg = 'recipe_id'

    def dispatch(self, *args, **kwargs):
        response = super(RecipeViewableMixin, self).dispatch(*args, **kwargs)
        if not self.object.can_be_viewed_by_user(self.request.user):
            raise http.Http404()
        return response


class RecipeSlugUrlMixin(object):
    def get_object(self, queryset=None):
        """
        Compensate the lack of django 1.7 : it can't query on both pk+slug
        """
        if not queryset:
            queryset = Recipe.objects.all()
        queryset = queryset.filter(slug_url=self.kwargs["slug"])
        return super(RecipeSlugUrlMixin, self).get_object(queryset)

apps/brew/templates/brew/add_mashstep_button.html
{% load i18n %}
<a 
    class="fm-create btn btn-primary btn-sm"
    data-fm-head="{% trans "Add mash step" %}"
    data-fm-callback="reload"
    href="{% url "brew_mash_add" object.id %}">
    {% trans "Add mash step" %} <span class="glyphicon glyphicon-plus"></span>
</a>

apps/brew/templates/brew/base_home.html
{% extends "base.html" %}
{% load i18n %}


{% block page %}
    <div class="jumbotron jumbotron-nav">
        <div class="container">
            <h1>
                {% block page_title %}
                {% endblock page_title %}
            </h1>
        </div>
        <hr class="before-nav">
        <div class="container">
            <ul class="nav nav-pills">
                <li role="presentation"><a href="/">{% trans "All recipes" %}</a></li>
                <li role="presentation"><a href="{% url "brew_recipe_users" %}">{% trans "By user" %}</a></li>
                <li role="presentation"><a href="{% url "brew_recipe_styles" %}">{% trans "By style" %}</a></li>
            </ul>
        </div>
    </div>
    {{ block.super }}
{% endblock page %}


{% block content %}

{% block page_content %}
{% endblock page_content %}

{% endblock content %}

apps/brew/templates/brew/beerstyle_list.html
{% extends "base.html" %}

{% load i18n %}


{% block page %}
    <div class="jumbotron jumbotron-nav">
        <div class="container">
            <h1>
                {% block title %}
                    {% trans "Beer styles" %} - {{ active_bjcp }}
                {% endblock title %}
            </h1>
        </div>
        <hr class="before-nav">
        <div class="container">

            <ul class="nav nav-pills" role="tablist">
                <li class="active">
                    <a href=".">
                        {% trans "Beer styles" %}
                    </a>
                </li>
            </ul>
        </div>
    </div>
    {{ block.super }}
{% endblock page %}


{% block content %}

<div class="well">
    Section en anglais seulement actuellement.
</div>

<table class="table">
    {% for style in object_list %}
        {% ifchanged style.category %}
            <p><br></p>
            <h3>{{ style.number }} - {{ style.category }}</h3>
        {% endifchanged %}
        
        <a href="{{ style.get_absolute_url }}">{{ style.get_number }} {{ style.name }}
        </a><br>
    {% endfor %}
</table>

{% endblock content %}

apps/brew/templates/brew/raw_misc_form.html
{% extends "brew/base_ingredient_form.html" %}
{% load i18n form_tags unit_tags %}

{% block table_content %}
    <thead>
        <tr>
            <th style="width:40px;" class='text-center'>#</th>
            <th>{% trans "Name" %}</th>
            <th>{% trans "Type" %}</th>
            <th>{% trans "Use for" %}</th>
        </tr>
    </thead>
    <tbody>
    {% for misc in form.get_ingredient_list %}
    <tr class='row_ingredient' data-json-object='{{ misc.json_object }}'>
        <td class='text-center'>
            <a href="#" class='btn btn-success btn-xs add-this-ingredient'>
                <span class="glyphicon glyphicon-plus"></span>
            </a>
        </td>
        <td>{{ misc.name }}</td>
        <td>{{ misc.get_misc_type_display }}</td>
        <td>{{ misc.get_use_in_display }}</td>
    </tr>
    {% endfor %}
    </tbody>
{% endblock table_content %}



{% block form_content %}

<div class="row">
    <div class="col-xs-6 col-sm-6 col-md-6 col-lg-6">
        {% addFormField form.amount %}
    </div>
    <div class="col-xs-6 col-sm-6 col-md-6 col-lg-6">
        {% addFormField form.use_in %}
    </div>
</div>
<div class="row">
    <div class="col-xs-6 col-sm-6 col-md-6 col-lg-6">
        {% addFormField form.time %}
    </div>
    <div class="col-xs-6 col-sm-6 col-md-6 col-lg-6">
        {% addFormField form.time_unit %}
    </div>
</div>
<div class="row">
    <div class="col-xs-6 col-sm-6 col-md-6 col-lg-6">
        {% addFormField form.name %}
    </div>
    <div class="col-xs-6 col-sm-6 col-md-6 col-lg-6">
        {% addFormField form.misc_type %}
    </div>
</div>
<div class="row">
    <div class="col-xs-6 col-sm-6 col-md-6 col-lg-6">
        {% addFormField form.usage %}
    </div>
    <div class="col-xs-6 col-sm-6 col-md-6 col-lg-6">
        {% addFormField form.notes %}
    </div>
</div>

{% endblock %}

apps/brew/templates/brew/recipe_form.html
{% extends "base.html" %}
{% load i18n form_tags static %}


{% block page %}
    <div class="jumbotron ">
        <div class="container">
            <h1>
                {% block title %}
					{% if form.instance.id %}
						{% trans "Edit" %} {{ form.instance }}
					{% else %}
						{% trans "Add a new recipe" %}
					{% endif %}
				{% endblock title %}
            </h1>
        </div>
    </div>
    {{ block.super }}
{% endblock page %}



{% block content %}

<form action="." method="POST" autocomplete="off" role="form">{% csrf_token %}

	<div class="vspace"></div>

{% comment %}
	
		'efficiency', 'private',
            '', '',
            'mash_tun_deadspace', '',
            'evaporation_rate', 'grain_temperature'
{% endcomment %}


	<div class="well form-help-inline">
		<div class="row">
			<div class="col-xs-3 col-sm-3 col-md-3 col-lg-3">
				{% addFormField form.batch_size simple=1 %}
			</div>
			<div class="col-xs-8 col-sm-8 col-md-8 col-lg-8">
				{% addFormField form.name simple=1 %}
			</div>
		</div>
		<div class="row">
			<div class="col-xs-3 col-sm-3 col-md-3 col-lg-3">
				{% addFormField form.efficiency simple=1 %}
			</div>
			<div class="col-xs-8 col-sm-8 col-md-8 col-lg-8">
				
				<div class="row">
					<div class="col-xs-6 col-sm-6 col-md-6 col-lg-6">
						{% addFormField form.recipe_type simple=1 %}
					</div>
					<div class="col-xs-6 col-sm-6 col-md-6 col-lg-6">
						{% addFormField form.recipe_style simple=1 %}
					</div>
				</div>
			</div>
		</div>
		
		<label for="{{ form.private.auto_id }}">
			<img src="{% static "images/fugue/lock.png" %}" alt="">
			{{ form.private }}
			{{ form.private.label }}
			<span class="text-muted">{{ form.private.help_text }}</span>
		</label>
	</div>
	<div class="vspace"></div>
	<fieldset class='form-horizontal form-help-inline small-input'>
		<legend>{% trans "Préférences" %}</legend>
		{% addFormField form.mash_tun_deadspace size="L" %}
		{% addFormField form.boiler_tun_deadspace size="L" %}
		{% addFormField form.evaporation_rate size="L" %}
		{% addFormField form.grain_temperature size="L" %}
	</fieldset>

	
	<hr>


	<div class="text-center">
		<input type="submit" class="btn btn-success btn-lg" value="{% if form.instance %}{% trans "Save" %}{% else %}{% trans "Add a new recipe" %}{% endif %}">
		{% if form.instance.id %}
			<a href="{{ form.instance.get_absolute_url }}" class="btn">{% trans "Return to recipe" %}</a>
		{% endif %}
	</div>

</form>

<div class="vspace-xl"></div>
<div class="vspace-xl"></div>

{% endblock content %}

{% block extrahead %}
<style type="text/css">

.row-private img{margin-bottom:4px;}
.preferences input{
	width:40px;
	text-align: center;
}
#id_batch_size, #id_efficiency, .small-input input{
	width:80px;
}
</style>
{% endblock extrahead %}

apps/brew/templates/brew/style_list.html
{% extends "brew/base_home.html" %}
{% load i18n %}


{% block title %}
    {% trans "All beer recipes by style" %}
{% endblock title %}


{% block page_title %}
    {% trans "By style" %}    
{% endblock page_title %}


{% block page_content %}
    <div class="well">
        {% url "brew_style_list" as style_list_url %}
        {% blocktrans %}
        Here are shown all the styles that have at least 1 recipe on Zython. <br>
        You can also see <a href="{{ style_list_url }}">all BJCP 2008 styles</a>
        {% endblocktrans %}
    </div>
    <table class="table">
        <thead>
            <tr>
                <th>{% trans "Style" %}</th>
                <th>{% trans "BJCP code" %}</th>
                <th>{% trans "Recipes" %}</th>
            </tr>
        </thead>
        <tbody>
            {% for object in object_list %}
                <tr>
                    <td><a href="{% url "brew_recipe_style" object.get_slug object.pk %}">{{ object }}</a></td>
                    <td>{{ object.get_number }}
{{ object.get_slug }}
                    </td>
                    <td>{{ object.recipe_set.all.count }}</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>

{% endblock page_content %}

apps/brew/templates/brew/style_recipe_list.html
{% extends "brew/base_home.html" %}
{% load i18n %}


{% block title %}
    {% trans "All recipes" %} {{ style }}
{% endblock title %}


{% block page_title %}
    {% trans "By style" %} > {{ style }}
{% endblock page_title %}


{% block page_content %}
    {% include "brew/recipe_list.part.html" %}

{% endblock page_content %}

apps/brew/templates/brew/user_list.html
{% extends "brew/base_home.html" %}
{% load i18n %}


{% block title %}
    {% trans "All beer recipes by user" %}
{% endblock title %}


{% block page_title %}
    {% trans "By user" %}    
{% endblock page_title %}


{% block page_content %}

    <table class="table">
        <thead>
            <tr>
                <th>{% trans "User" %}</th>
                <th>{% trans "Date joined" %}</th>
                <th>{% trans "Recipes" %}</th>
            </tr>
        </thead>
        <tbody>
            {% for object in object_list %}
                <tr>
                    <td><a href="{% url "brew_recipe_user" object.username %}">{{ object.username }}</a></td>
                    <td>{{ object.date_joined|date:"d b Y" }}</td>
                    <td>{{ object.recipe_set.all.count }}</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>

{% endblock page_content %}